name: "✨ Feature Request"
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
        Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe it.
      placeholder: A clear description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: Alternative solutions or workarounds...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Nice to have"
        - "Important"
        - "Critical"
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area of the website does this affect?
      multiple: true
      options:
        - "Homepage / Hero"
        - "Services Section"
        - "Portfolio Section"
        - "Technology Section"
        - "Team Section"
        - "Contact Form"
        - "Chat Widget"
        - "Navigation"
        - "Footer"
        - "Accessibility"
        - "Performance"
        - "Security"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If you have any mockups or examples, please share them
      placeholder: Drag and drop images or paste links...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
